#!/bin/bash
echo "🔍 GitHubリポジトリを探しています..."
echo ""
echo "以下の手順でリポジトリURLを見つけてください:"
echo ""
echo "1. ブラウザで https://github.com を開く"
echo "2. 右上のプロフィールアイコンをクリック"
echo "3. 'Your repositories' をクリック"
echo "4. 'neighborhoods-portfolio' をクリック"
echo "5. 緑色の 'Code' ボタンをクリック"
echo "6. 表示されるURLをコピー（例: https://github.com/username/neighborhoods-portfolio.git）"
echo ""
echo "URLをコピーしたら、以下のコマンドを実行してください:"
echo "./quick-deploy.sh"
echo ""
echo "または、URLを直接教えてください。自動で設定します。"
